// <auto-generated />
using System;
using LarsV2.Models.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LarsV2.Migrations
{
    [DbContext(typeof(LecturerDbContext))]
    [Migration("20211118164314_AddedMoreSeedData")]
    partial class AddedMoreSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LarsV2.Models.Entities.Lecturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CVPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("bit");

                    b.Property<string>("Knowledge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Lecturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "jan@eamv.dk",
                            FirstName = "Jan Pan",
                            IsExternal = false,
                            LastName = "Nees",
                            PhoneNumber = "+4512345678"
                        },
                        new
                        {
                            Id = 2,
                            Email = "jameshetfield@metallica.com",
                            FirstName = "James",
                            IsExternal = false,
                            LastName = "Hetfield",
                            PhoneNumber = "+4569696969"
                        },
                        new
                        {
                            Id = 3,
                            Email = "flemming@eamv.dk",
                            FirstName = "Flemming",
                            IsExternal = false,
                            LastName = "Efternavn",
                            PhoneNumber = "+4511111111"
                        },
                        new
                        {
                            Id = 4,
                            Email = "lindemann@eamv.dk",
                            FirstName = "Till",
                            IsExternal = false,
                            LastName = "Lindemann",
                            PhoneNumber = "+4598765432"
                        },
                        new
                        {
                            Id = 5,
                            Email = "bob@eamv.dk",
                            FirstName = "Bob",
                            IsExternal = false,
                            LastName = "Ross",
                            PhoneNumber = "+4544444444"
                        },
                        new
                        {
                            Id = 6,
                            Email = "putin@eamv.dk",
                            FirstName = "Vladimir",
                            IsExternal = false,
                            LastName = "Putin",
                            PhoneNumber = "+4555555555"
                        },
                        new
                        {
                            Id = 7,
                            Email = "trump@eamv.dk",
                            FirstName = "Donald",
                            IsExternal = false,
                            LastName = "Trump",
                            PhoneNumber = "+4566666666"
                        },
                        new
                        {
                            Id = 8,
                            Email = "joe@eamv.dk",
                            FirstName = "Joe",
                            IsExternal = false,
                            LastName = "Rogan",
                            PhoneNumber = "+4577777777"
                        },
                        new
                        {
                            Id = 9,
                            Email = "max@eamv.dk",
                            FirstName = "Max",
                            IsExternal = false,
                            LastName = "Verstappen",
                            PhoneNumber = "+4588888888"
                        },
                        new
                        {
                            Id = 10,
                            Email = "messi@eamv.dk",
                            FirstName = "Lionel",
                            IsExternal = false,
                            LastName = "Messi",
                            PhoneNumber = "+4599999999"
                        },
                        new
                        {
                            Id = 11,
                            Email = "ronaldo@eamv.dk",
                            FirstName = "Cristiano",
                            IsExternal = false,
                            LastName = "Ronaldo",
                            PhoneNumber = "+4512121212"
                        },
                        new
                        {
                            Id = 12,
                            Email = "maynard@eamv.dk",
                            FirstName = "Maynard James",
                            IsExternal = false,
                            LastName = "Keenan",
                            PhoneNumber = "+4569696969"
                        },
                        new
                        {
                            Id = 13,
                            Email = "steven@eamv.dk",
                            FirstName = "Steven",
                            IsExternal = false,
                            LastName = "Wilson",
                            PhoneNumber = "+4512341234"
                        });
                });

            modelBuilder.Entity("LarsV2.Models.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Education")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LecturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("LecturerId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("LarsV2.Models.Entities.Subject", b =>
                {
                    b.HasOne("LarsV2.Models.Entities.Lecturer", null)
                        .WithMany("Subjects")
                        .HasForeignKey("LecturerId");
                });

            modelBuilder.Entity("LarsV2.Models.Entities.Lecturer", b =>
                {
                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
